branch-defaults:
  develop:
    environment: code-compiler-service-stage
  master:
    environment: code-compiler-service-production
global:
  application_name: code-compiler-service
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Node.js 12 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
